// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { enc, type CallOptions } from "../core.js";
import type { Paginator } from "../pagination.js";
import type {
  Account,
  AccountPresenceRequestState,
  AccountsCreatePairingCodeParams,
  AccountsCreateParams,
  AccountsListParams,
  AccountsSetDefaultDisappearingTimerParams,
  AccountsSetPresenceParams,
  AccountsUpdateParams,
  DisappearingTimerRequestDurationSeconds,
  PairingCode,
} from "../types.js";
import { AccountsBase } from "../custom/index.js";

/**
 * An account is one WhatsApp number linked as a device, by QR code or by pairing code. Create one, show `qrCodeUrl` to the phone owner or have them type `pairingCode`, and wait for `ready`. Routes under `/v1/accounts/{accountId}` that talk to WhatsApp need the account `ready` (otherwise `409 account_not_ready`).
 *
 * An account is billable once it has finished linking (`linkedAt` is set), until it is deleted or logged out.
 */
export class AccountsResource extends AccountsBase {
  /**
   * List accounts
   *
   * Accounts in scope, newest first. Deleted accounts are not listed.
   *
   * `GET /v1/accounts`
   */
  list(params: AccountsListParams = {}, options?: CallOptions): Paginator<Account, AccountsListParams> {
    return this._list<Account, AccountsListParams>(
      "/v1/accounts",
      params,
      (p) => ({ limit: p.limit, cursor: p.cursor, projectId: p.projectId }),
      options,
    );
  }

  /**
   * Create an account
   *
   * Start linking a new WhatsApp number. Choose where its residential proxy exits with `proxyLocation`, a pair from `GET /v1/proxy-locations` (ideally the number's own country). The account is returned with `status: initializing`. Poll `GET /v1/accounts/{accountId}` (or listen for `account.qr_code_issued`) until `status` is `qr_ready`, show `qrCodeUrl` to the phone owner (WhatsApp > Linked devices > Link a device), then wait for `ready`.
   *
   * To link by phone number instead, pass `pairingPhone`: the code appears as `pairingCode` (and the `account.pairing_code_issued` event) once the session is up. For a page someone else opens to link their own number, use `POST /v1/invitations`.
   *
   * Chat history is not imported unless you pass `historySync: recent`. WhatsApp sends recent history once, right after the number links; those messages are stored with `source: history` and `history.synced` fires.
   *
   * Requires an active subscription. Inside a project, `maxAccounts` applies.
   *
   * `POST /v1/accounts`
   */
  create(params: AccountsCreateParams, options?: CallOptions): Promise<Account> {
    return this._request<Account>("POST", "/v1/accounts", { body: params, idempotent: true }, options);
  }

  /**
   * Get an account
   *
   * The account, with its current QR code or pairing code while it links.
   *
   * `GET /v1/accounts/{accountId}`
   */
  get(accountId: string, options?: CallOptions): Promise<Account> {
    return this._request<Account>("GET", `/v1/accounts/${enc(accountId)}`, {}, options);
  }

  /**
   * Update an account
   *
   * Rename it, set automatic call rejection, or turn on and tune its pacing (anti-ban protections, off by default). Call settings are sent to the live session (the engine must know the account; it does not need to be `ready`). Pacing applies from the next send, without reconnecting. `imageQuality` applies to the images sent from then on. `historySync` is stored at once and applies to the next link: WhatsApp sends history only right after a number links. A `proxyLocation` change is checked before anything else is applied: a refused location (`400` or `429`) leaves the whole request unapplied.
   *
   * `PATCH /v1/accounts/{accountId}`
   */
  update(accountId: string, params: AccountsUpdateParams = {}, options?: CallOptions): Promise<Account> {
    return this._request<Account>("PATCH", `/v1/accounts/${enc(accountId)}`, { body: params }, options);
  }

  /**
   * Delete an account
   *
   * Log the session out on WhatsApp, delete the account and stop billing for it. Fires no event.
   *
   * `DELETE /v1/accounts/{accountId}`
   */
  delete(accountId: string, options?: CallOptions): Promise<void> {
    return this._request<void>("DELETE", `/v1/accounts/${enc(accountId)}`, {}, options);
  }

  /**
   * Reconnect an account
   *
   * Restart the session. Produces a fresh QR code (or pairing code) when the link is no longer valid.
   *
   * `POST /v1/accounts/{accountId}/reconnect`
   */
  reconnect(accountId: string, options?: CallOptions): Promise<Account> {
    return this._request<Account>(
      "POST",
      `/v1/accounts/${enc(accountId)}/reconnect`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Log an account out
   *
   * Unlink the phone and stop billing, keeping the account and its messages. Reconnect to link again.
   *
   * `POST /v1/accounts/{accountId}/logout`
   */
  logout(accountId: string, options?: CallOptions): Promise<Account> {
    return this._request<Account>(
      "POST",
      `/v1/accounts/${enc(accountId)}/logout`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Create a pairing code
   *
   * Link by phone number instead of QR code: returns an 8-character code the phone owner types in WhatsApp > Linked devices > Link a device > Link with phone number instead. Works while the account is not linked (a session the engine lost is recreated first). The code lives about 160 seconds; ask again after `expiresAt`.
   *
   * `POST /v1/accounts/{accountId}/pairing-code`
   */
  createPairingCode(
    accountId: string,
    params: AccountsCreatePairingCodeParams,
    options?: CallOptions,
  ): Promise<PairingCode> {
    return this._request<PairingCode>(
      "POST",
      `/v1/accounts/${enc(accountId)}/pairing-code`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Set online or offline
   *
   * Show the account as online or offline to contacts.
   *
   * `POST /v1/accounts/{accountId}/presence`
   */
  setPresence(accountId: string, params: AccountsSetPresenceParams, options?: CallOptions): Promise<void>;
  /** @deprecated Pass `{ state }`. This positional form goes away in 1.0. */
  setPresence(accountId: string, state: AccountPresenceRequestState, options?: CallOptions): Promise<void>;
  setPresence(
    accountId: string,
    params: AccountsSetPresenceParams | AccountPresenceRequestState,
    options?: CallOptions,
  ): Promise<void> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<void>(
        "POST",
        `/v1/accounts/${enc(accountId)}/presence`,
        { body: { state: params }, idempotent: true },
        options,
      );
    }
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/presence`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Set the default disappearing timer
   *
   * The timer new chats start with.
   *
   * `PUT /v1/accounts/{accountId}/disappearing-timer`
   */
  setDefaultDisappearingTimer(
    accountId: string,
    params: AccountsSetDefaultDisappearingTimerParams,
    options?: CallOptions,
  ): Promise<void>;
  /** @deprecated Pass `{ durationSeconds }`. This positional form goes away in 1.0. */
  setDefaultDisappearingTimer(
    accountId: string,
    durationSeconds: DisappearingTimerRequestDurationSeconds,
    options?: CallOptions,
  ): Promise<void>;
  setDefaultDisappearingTimer(
    accountId: string,
    params: AccountsSetDefaultDisappearingTimerParams | DisappearingTimerRequestDurationSeconds,
    options?: CallOptions,
  ): Promise<void> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<void>(
        "PUT",
        `/v1/accounts/${enc(accountId)}/disappearing-timer`,
        { body: { durationSeconds: params } },
        options,
      );
    }
    return this._request<void>(
      "PUT",
      `/v1/accounts/${enc(accountId)}/disappearing-timer`,
      { body: params },
      options,
    );
  }
}
