// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { enc, type CallOptions } from "../core.js";
import type { Paginator } from "../pagination.js";
import type { Bot, BotsListParams } from "../types.js";
import { Resource } from "./base.js";

export class BotsResource extends Resource {
  /**
   * List WhatsApp AI bots
   *
   * WhatsApp's AI bot directory as the account sees it. `400 not_supported` when WhatsApp does not offer it to this account (WhatsApp's AI assistant is not available in every country or on every account).
   *
   * `GET /v1/accounts/{accountId}/bots`
   */
  list(
    accountId: string,
    params: BotsListParams = {},
    options?: CallOptions,
  ): Paginator<Bot, BotsListParams> {
    return this._list<Bot, BotsListParams>(
      `/v1/accounts/${enc(accountId)}/bots`,
      params,
      (p) => ({ limit: p.limit, cursor: p.cursor }),
      options,
    );
  }
}
