// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { type CallOptions } from "../core.js";
import type { Branding, BrandingUpdateParams } from "../types.js";
import { Resource } from "./base.js";

/**
 * What the invitation page and email show: your name, logo, accent color, support link, and whether the wuapi footer appears (hiding it needs the White label add-on).
 */
export class BrandingResource extends Resource {
  /**
   * Get branding
   *
   * What the invitation page and email show. Organization keys only (project keys get `403 forbidden`); the `Wuapi-Project` header does not change the result.
   *
   * `GET /v1/branding`
   */
  get(options?: CallOptions): Promise<Branding> {
    return this._request<Branding>("GET", "/v1/branding", {}, options);
  }

  /**
   * Update branding
   *
   * `displayName` is required the first time. Without an accent color the page uses wuapi's own. `hideWuapiBranding: true` needs the White label add-on ($100/month): without it the call answers `402 addon_required` and changes nothing. Organization keys only (project keys get `403 forbidden`); the `Wuapi-Project` header does not change the result.
   *
   * `PATCH /v1/branding`
   */
  update(params: BrandingUpdateParams = {}, options?: CallOptions): Promise<Branding> {
    return this._request<Branding>("PATCH", "/v1/branding", { body: params }, options);
  }
}
