// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { enc, type CallOptions } from "../core.js";
import type { CallsRejectParams } from "../types.js";
import { Resource } from "./base.js";

/**
 * Reject incoming calls. Automatic rejection is a setting on the account (`PATCH /v1/accounts/{accountId}`).
 */
export class CallsResource extends Resource {
  /**
   * Reject an incoming call
   *
   * Use the `id` and `from` of a `call.received` event. For automatic rejection, set `rejectCalls` on the account.
   *
   * `POST /v1/accounts/{accountId}/calls/{callId}/reject`
   */
  reject(accountId: string, callId: string, params: CallsRejectParams, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/calls/${enc(callId)}/reject`,
      { body: params, idempotent: true },
      options,
    );
  }
}
