// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { enc, type CallOptions } from "../core.js";
import type { Paginator } from "../pagination.js";
import type {
  Channel,
  ChannelMessage,
  ChannelsCreateParams,
  ChannelsListMessagesParams,
  ChannelsListParams,
  ChannelsMarkViewedParams,
  ChannelsReactParams,
} from "../types.js";
import { Resource } from "./base.js";

/**
 * WhatsApp channels: follow, read, react. Post with `POST /v1/messages` and `to` set to the channel id.
 */
export class ChannelsResource extends Resource {
  /**
   * List followed channels
   *
   * Channels the account follows, read live from WhatsApp.
   *
   * `GET /v1/accounts/{accountId}/channels`
   */
  list(
    accountId: string,
    params: ChannelsListParams = {},
    options?: CallOptions,
  ): Paginator<Channel, ChannelsListParams> {
    return this._list<Channel, ChannelsListParams>(
      `/v1/accounts/${enc(accountId)}/channels`,
      params,
      (p) => ({ limit: p.limit, cursor: p.cursor }),
      options,
    );
  }

  /**
   * Create a channel
   *
   * The account becomes its owner. Post to it with `POST /v1/messages` and `to` set to its id.
   *
   * `POST /v1/accounts/{accountId}/channels`
   */
  create(accountId: string, params: ChannelsCreateParams, options?: CallOptions): Promise<Channel> {
    return this._request<Channel>(
      "POST",
      `/v1/accounts/${enc(accountId)}/channels`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Preview a channel invite
   *
   * The channel behind an invite code.
   *
   * `GET /v1/accounts/{accountId}/channels/invites/{code}`
   */
  getInvite(accountId: string, code: string, options?: CallOptions): Promise<Channel> {
    return this._request<Channel>(
      "GET",
      `/v1/accounts/${enc(accountId)}/channels/invites/${enc(code)}`,
      {},
      options,
    );
  }

  /**
   * Get a channel
   *
   * A channel, read live from WhatsApp.
   *
   * `GET /v1/accounts/{accountId}/channels/{channelId}`
   */
  get(accountId: string, channelId: string, options?: CallOptions): Promise<Channel> {
    return this._request<Channel>(
      "GET",
      `/v1/accounts/${enc(accountId)}/channels/${enc(channelId)}`,
      {},
      options,
    );
  }

  /**
   * Follow a channel
   *
   * Start receiving the channel's messages.
   *
   * `POST /v1/accounts/{accountId}/channels/{channelId}/follow`
   */
  follow(accountId: string, channelId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/channels/${enc(channelId)}/follow`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Unfollow a channel
   *
   * Stop following the channel.
   *
   * `POST /v1/accounts/{accountId}/channels/{channelId}/unfollow`
   */
  unfollow(accountId: string, channelId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/channels/${enc(channelId)}/unfollow`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Mute a channel
   *
   * Mute the channel's notifications.
   *
   * `POST /v1/accounts/{accountId}/channels/{channelId}/mute`
   */
  mute(accountId: string, channelId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/channels/${enc(channelId)}/mute`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Unmute a channel
   *
   * Turn the channel's notifications back on.
   *
   * `POST /v1/accounts/{accountId}/channels/{channelId}/unmute`
   */
  unmute(accountId: string, channelId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/channels/${enc(channelId)}/unmute`,
      { idempotent: true },
      options,
    );
  }

  /**
   * List a channel's messages
   *
   * Messages in the channel, newest first, read live from WhatsApp.
   *
   * `GET /v1/accounts/{accountId}/channels/{channelId}/messages`
   */
  listMessages(
    accountId: string,
    channelId: string,
    params: ChannelsListMessagesParams = {},
    options?: CallOptions,
  ): Paginator<ChannelMessage, ChannelsListMessagesParams> {
    return this._list<ChannelMessage, ChannelsListMessagesParams>(
      `/v1/accounts/${enc(accountId)}/channels/${enc(channelId)}/messages`,
      params,
      (p) => ({ limit: p.limit, cursor: p.cursor }),
      options,
    );
  }

  /**
   * React to a channel message
   *
   * An empty `emoji` removes the reaction.
   *
   * `POST /v1/accounts/{accountId}/channels/{channelId}/messages/{channelMessageId}/react`
   */
  react(
    accountId: string,
    channelId: string,
    channelMessageId: string,
    params: ChannelsReactParams,
    options?: CallOptions,
  ): Promise<void>;
  /** @deprecated Pass `{ emoji }`. This positional form goes away in 1.0. */
  react(
    accountId: string,
    channelId: string,
    channelMessageId: string,
    emoji: string,
    options?: CallOptions,
  ): Promise<void>;
  react(
    accountId: string,
    channelId: string,
    channelMessageId: string,
    params: ChannelsReactParams | string,
    options?: CallOptions,
  ): Promise<void> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<void>(
        "POST",
        `/v1/accounts/${enc(accountId)}/channels/${enc(channelId)}/messages/${enc(channelMessageId)}/react`,
        { body: { emoji: params }, idempotent: true },
        options,
      );
    }
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/channels/${enc(channelId)}/messages/${enc(channelMessageId)}/react`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Mark channel messages viewed
   *
   * Count the account as a viewer of these messages.
   *
   * `POST /v1/accounts/{accountId}/channels/{channelId}/mark-viewed`
   */
  markViewed(
    accountId: string,
    channelId: string,
    params: ChannelsMarkViewedParams,
    options?: CallOptions,
  ): Promise<void>;
  /** @deprecated Pass `{ channelMessageIds }`. This positional form goes away in 1.0. */
  markViewed(
    accountId: string,
    channelId: string,
    channelMessageIds: string[],
    options?: CallOptions,
  ): Promise<void>;
  markViewed(
    accountId: string,
    channelId: string,
    params: ChannelsMarkViewedParams | string[],
    options?: CallOptions,
  ): Promise<void> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<void>(
        "POST",
        `/v1/accounts/${enc(accountId)}/channels/${enc(channelId)}/mark-viewed`,
        { body: { channelMessageIds: params }, idempotent: true },
        options,
      );
    }
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/channels/${enc(channelId)}/mark-viewed`,
      { body: params, idempotent: true },
      options,
    );
  }
}
