// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { enc, type CallOptions } from "../core.js";
import type { Paginator } from "../pagination.js";
import type {
  Chat,
  ChatPresenceRequestState,
  ChatRead,
  ChatsAddLabelParams,
  ChatsDeleteParams,
  ChatsListParams,
  ChatsMuteParams,
  ChatsSendPresenceParams,
  ChatsSendReadReceiptsParams,
  ChatsSetDisappearingTimerParams,
  DisappearingTimerRequestDurationSeconds,
} from "../types.js";
import { Resource } from "./base.js";

export class ChatsResource extends Resource {
  /**
   * List chats
   *
   * The account's chats, the one with the newest message first: every conversation with a contact, group or channel that wuapi holds a message of, each with its latest message and WhatsApp's unread, pinned, archived and muted state. A state wuapi does not know yet is `null` (see `Chat`). The filters combine, and a page of combined filters may hold fewer chats than `limit` while `nextCursor` is set: keep following the cursor. With `q`, the chats that match, best match first.
   *
   * `GET /v1/accounts/{accountId}/chats`
   */
  list(
    accountId: string,
    params: ChatsListParams = {},
    options?: CallOptions,
  ): Paginator<Chat, ChatsListParams> {
    return this._list<Chat, ChatsListParams>(
      `/v1/accounts/${enc(accountId)}/chats`,
      params,
      (p) => ({ archived: p.archived, unread: p.unread, type: p.type, q: p.q, limit: p.limit, cursor: p.cursor }),
      options,
    );
  }

  /**
   * Get a chat
   *
   * One chat of the account, with its latest message and WhatsApp's unread, pinned, archived and muted state. A chat wuapi holds no message of answers `404 not_found`.
   *
   * `GET /v1/accounts/{accountId}/chats/{chatId}`
   */
  get(accountId: string, chatId: string, options?: CallOptions): Promise<Chat> {
    return this._request<Chat>("GET", `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}`, {}, options);
  }

  /**
   * Show typing or recording
   *
   * Show (`typing`, `recording`) or clear (`paused`) the indicator in a chat.
   *
   * `POST /v1/accounts/{accountId}/chats/{chatId}/presence`
   */
  sendPresence(
    accountId: string,
    chatId: string,
    params: ChatsSendPresenceParams,
    options?: CallOptions,
  ): Promise<void>;
  /** @deprecated Pass `{ state }`. This positional form goes away in 1.0. */
  sendPresence(
    accountId: string,
    chatId: string,
    state: ChatPresenceRequestState,
    options?: CallOptions,
  ): Promise<void>;
  sendPresence(
    accountId: string,
    chatId: string,
    params: ChatsSendPresenceParams | ChatPresenceRequestState,
    options?: CallOptions,
  ): Promise<void> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<void>(
        "POST",
        `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}/presence`,
        { body: { state: params }, idempotent: true },
        options,
      );
    }
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}/presence`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Send read receipts
   *
   * Send read receipts (blue ticks) for messages in a chat. Without `messageIds`, every unread inbound message wuapi stores for the chat. In a group WhatsApp takes one receipt per author, so this makes one change per author.
   *
   * `POST /v1/accounts/{accountId}/chats/{chatId}/read`
   */
  sendReadReceipts(
    accountId: string,
    chatId: string,
    params: ChatsSendReadReceiptsParams = {},
    options?: CallOptions,
  ): Promise<ChatRead> {
    return this._request<ChatRead>(
      "POST",
      `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}/read`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Mark a chat read
   *
   * Clear the chat's unread badge on the phone and other devices. Sends no read receipts; use `POST .../read` for those.
   *
   * `POST /v1/accounts/{accountId}/chats/{chatId}/mark-read`
   */
  markRead(accountId: string, chatId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}/mark-read`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Mark a chat unread
   *
   * Put the unread badge back on the chat.
   *
   * `POST /v1/accounts/{accountId}/chats/{chatId}/mark-unread`
   */
  markUnread(accountId: string, chatId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}/mark-unread`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Archive a chat
   *
   * Archive the chat on the phone and other devices.
   *
   * `POST /v1/accounts/{accountId}/chats/{chatId}/archive`
   */
  archive(accountId: string, chatId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}/archive`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Unarchive a chat
   *
   * Move the chat out of the archive.
   *
   * `POST /v1/accounts/{accountId}/chats/{chatId}/unarchive`
   */
  unarchive(accountId: string, chatId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}/unarchive`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Pin a chat
   *
   * Pin the chat to the top.
   *
   * `POST /v1/accounts/{accountId}/chats/{chatId}/pin`
   */
  pin(accountId: string, chatId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}/pin`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Unpin a chat
   *
   * Unpin the chat.
   *
   * `POST /v1/accounts/{accountId}/chats/{chatId}/unpin`
   */
  unpin(accountId: string, chatId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}/unpin`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Mute a chat
   *
   * Mute notifications for the chat, for `durationSeconds` or until unmuted.
   *
   * `POST /v1/accounts/{accountId}/chats/{chatId}/mute`
   */
  mute(
    accountId: string,
    chatId: string,
    params: ChatsMuteParams = {},
    options?: CallOptions,
  ): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}/mute`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Unmute a chat
   *
   * Turn the chat's notifications back on.
   *
   * `POST /v1/accounts/{accountId}/chats/{chatId}/unmute`
   */
  unmute(accountId: string, chatId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}/unmute`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Delete a chat
   *
   * Delete the chat on the linked devices. Messages stored in wuapi are kept.
   *
   * `DELETE /v1/accounts/{accountId}/chats/{chatId}`
   */
  delete(
    accountId: string,
    chatId: string,
    params: ChatsDeleteParams = {},
    options?: CallOptions,
  ): Promise<void> {
    return this._request<void>(
      "DELETE",
      `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}`,
      { query: { deleteMedia: params.deleteMedia } },
      options,
    );
  }

  /**
   * Set a chat's disappearing timer
   *
   * Messages in the chat disappear after `durationSeconds`; 0 turns it off.
   *
   * `PUT /v1/accounts/{accountId}/chats/{chatId}/disappearing-timer`
   */
  setDisappearingTimer(
    accountId: string,
    chatId: string,
    params: ChatsSetDisappearingTimerParams,
    options?: CallOptions,
  ): Promise<void>;
  /** @deprecated Pass `{ durationSeconds }`. This positional form goes away in 1.0. */
  setDisappearingTimer(
    accountId: string,
    chatId: string,
    durationSeconds: DisappearingTimerRequestDurationSeconds,
    options?: CallOptions,
  ): Promise<void>;
  setDisappearingTimer(
    accountId: string,
    chatId: string,
    params: ChatsSetDisappearingTimerParams | DisappearingTimerRequestDurationSeconds,
    options?: CallOptions,
  ): Promise<void> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<void>(
        "PUT",
        `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}/disappearing-timer`,
        { body: { durationSeconds: params } },
        options,
      );
    }
    return this._request<void>(
      "PUT",
      `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}/disappearing-timer`,
      { body: params },
      options,
    );
  }

  /**
   * Label a chat
   *
   * WhatsApp Business accounts only; others answer `400 not_supported`.
   *
   * `POST /v1/accounts/{accountId}/chats/{chatId}/labels`
   */
  addLabel(
    accountId: string,
    chatId: string,
    params: ChatsAddLabelParams,
    options?: CallOptions,
  ): Promise<void>;
  /** @deprecated Pass `{ labelId }`. This positional form goes away in 1.0. */
  addLabel(accountId: string, chatId: string, labelId: string, options?: CallOptions): Promise<void>;
  addLabel(
    accountId: string,
    chatId: string,
    params: ChatsAddLabelParams | string,
    options?: CallOptions,
  ): Promise<void> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<void>(
        "POST",
        `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}/labels`,
        { body: { labelId: params }, idempotent: true },
        options,
      );
    }
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}/labels`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Remove a label from a chat
   *
   * WhatsApp Business accounts only.
   *
   * `DELETE /v1/accounts/{accountId}/chats/{chatId}/labels/{labelId}`
   */
  removeLabel(accountId: string, chatId: string, labelId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "DELETE",
      `/v1/accounts/${enc(accountId)}/chats/${enc(chatId)}/labels/${enc(labelId)}`,
      {},
      options,
    );
  }
}
