// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { enc, type CallOptions } from "../core.js";
import type { Paginator } from "../pagination.js";
import type {
  BlockedContact,
  BusinessProfile,
  Contact,
  ContactCheck,
  ContactCheckList,
  ContactLink,
  ContactList,
  ContactsCheckParams,
  ContactsGetPictureParams,
  ContactsListBlockedParams,
  ContactsListParams,
  ContactsLookupParams,
  ContactsResolveLinkParams,
  Picture,
  ResolvedLink,
} from "../types.js";
import { Resource } from "./base.js";

export class ContactsResource extends Resource {
  /**
   * List contacts
   *
   * The account's contacts, ordered by saved name: its address book as the linked phone synced it to wuapi. Read from what wuapi stored, without asking WhatsApp, so it works while the account is not `ready`.
   *
   * What is in it: every contact the phone holds a saved name or a business name for. WhatsApp sends the address book to a linked device when the number is linked and again whenever it resyncs it, and wuapi stores it then, and after that every contact the phone adds, renames or deletes, as it happens. So the list is empty until the first sync after linking finishes (seconds to a few minutes), a contact deleted on the phone leaves the list, and people the account only chatted with, without saving them, are not in it: those are in `GET …/chats`.
   *
   * `about` and `deviceCount` are `null` here (ask `POST …/contacts/lookup`); `username` and `pictureId` are what wuapi has seen so far. With `q`, the contacts that match, best match first.
   *
   * `GET /v1/accounts/{accountId}/contacts`
   */
  list(
    accountId: string,
    params: ContactsListParams = {},
    options?: CallOptions,
  ): Paginator<Contact, ContactsListParams> {
    return this._list<Contact, ContactsListParams>(
      `/v1/accounts/${enc(accountId)}/contacts`,
      params,
      (p) => ({ q: p.q, limit: p.limit, cursor: p.cursor }),
      options,
    );
  }

  /**
   * Get a contact
   *
   * One contact of the account's address book, by its number or its `lid:<digits>` id, from what wuapi stored (see `GET …/contacts` for what that holds). A number or id the address book does not hold answers `404 not_found`, even when the account has a chat with it: `POST …/contacts/lookup` asks WhatsApp about any number.
   *
   * `GET /v1/accounts/{accountId}/contacts/{contactId}`
   */
  get(accountId: string, contactId: string, options?: CallOptions): Promise<Contact> {
    return this._request<Contact>(
      "GET",
      `/v1/accounts/${enc(accountId)}/contacts/${enc(contactId)}`,
      {},
      options,
    );
  }

  /**
   * Check numbers on WhatsApp
   *
   * Which numbers have WhatsApp. Read-only: works for a suspended project.
   *
   * `POST /v1/accounts/{accountId}/contacts/check`
   */
  check(accountId: string, params: ContactsCheckParams, options?: CallOptions): Promise<ContactCheckList>;
  /**
   * @deprecated Pass `{ phones }` and read `items` of the result. This positional form and its bare result go away in 1.0.
   */
  check(accountId: string, phones: string[], options?: CallOptions): Promise<ContactCheck[]>;
  check(
    accountId: string,
    params: ContactsCheckParams | string[],
    options?: CallOptions,
  ): Promise<ContactCheckList | ContactCheck[]> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<ContactCheckList>(
        "POST",
        `/v1/accounts/${enc(accountId)}/contacts/check`,
        { body: { phones: params }, idempotent: true },
        options,
      ).then((res) => res.items);
    }
    return this._request<ContactCheckList>(
      "POST",
      `/v1/accounts/${enc(accountId)}/contacts/check`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Look up contacts
   *
   * About text, picture id, verified business name, username and device count, asked from WhatsApp for 1 to 50 contacts. Read-only. `savedName` and `profileName` are `null` here: the account's address book is `GET …/contacts`. The picture ids and usernames it returns are kept on the chats and contacts wuapi stores.
   *
   * `POST /v1/accounts/{accountId}/contacts/lookup`
   */
  lookup(accountId: string, params: ContactsLookupParams, options?: CallOptions): Promise<ContactList>;
  /**
   * @deprecated Pass `{ contactIds }` and read `items` of the result. This positional form and its bare result go away in 1.0.
   */
  lookup(accountId: string, contactIds: string[], options?: CallOptions): Promise<Contact[]>;
  lookup(
    accountId: string,
    params: ContactsLookupParams | string[],
    options?: CallOptions,
  ): Promise<ContactList | Contact[]> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<ContactList>(
        "POST",
        `/v1/accounts/${enc(accountId)}/contacts/lookup`,
        { body: { contactIds: params }, idempotent: true },
        options,
      ).then((res) => res.items);
    }
    return this._request<ContactList>(
      "POST",
      `/v1/accounts/${enc(accountId)}/contacts/lookup`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Get a profile picture
   *
   * The profile picture of a contact, or the picture of a group: `{contactId}` also takes a group id (`120363041234567890@g.us`), which is how a chat list shows group pictures. `id` is the picture's id and `url` a WhatsApp URL that expires, so download it and keep it by `id`. `404 picture_not_found` when it has no picture or this account may not see it (the contact's privacy settings); a community's own picture may answer that too. A channel id is passed to WhatsApp as it is, with no guarantee of an answer: a channel's picture is `pictureUrl` on the channel.
   *
   * What this call learns is kept: `pictureId` of the chat and of the contact follows it, so check that field before asking again.
   *
   * `GET /v1/accounts/{accountId}/contacts/{contactId}/picture`
   */
  getPicture(
    accountId: string,
    contactId: string,
    params: ContactsGetPictureParams = {},
    options?: CallOptions,
  ): Promise<Picture> {
    return this._request<Picture>(
      "GET",
      `/v1/accounts/${enc(accountId)}/contacts/${enc(contactId)}/picture`,
      { query: { preview: params.preview } },
      options,
    );
  }

  /**
   * Get a business profile
   *
   * The WhatsApp Business profile of a contact.
   *
   * `GET /v1/accounts/{accountId}/contacts/{contactId}/business-profile`
   */
  getBusinessProfile(accountId: string, contactId: string, options?: CallOptions): Promise<BusinessProfile> {
    return this._request<BusinessProfile>(
      "GET",
      `/v1/accounts/${enc(accountId)}/contacts/${enc(contactId)}/business-profile`,
      {},
      options,
    );
  }

  /**
   * Subscribe to a contact's presence
   *
   * Receive `contact.presence_updated` events for the contact. Needs the engine's extended events; otherwise `400 not_supported`.
   *
   * `POST /v1/accounts/{accountId}/contacts/{contactId}/subscribe-presence`
   */
  subscribePresence(accountId: string, contactId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/contacts/${enc(contactId)}/subscribe-presence`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Block a contact
   *
   * The contact can no longer message or call the account.
   *
   * `POST /v1/accounts/{accountId}/contacts/{contactId}/block`
   */
  block(accountId: string, contactId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/contacts/${enc(contactId)}/block`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Unblock a contact
   *
   * Remove the contact from the blocklist.
   *
   * `POST /v1/accounts/{accountId}/contacts/{contactId}/unblock`
   */
  unblock(accountId: string, contactId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/contacts/${enc(contactId)}/unblock`,
      { idempotent: true },
      options,
    );
  }

  /**
   * List blocked contacts
   *
   * The account's blocklist, read live from WhatsApp. `contactId` is the contact as WhatsApp lists it (often a LID); `phone` and `lid` add the number and the LID when the account knows them.
   *
   * `GET /v1/accounts/{accountId}/blocklist`
   */
  listBlocked(
    accountId: string,
    params: ContactsListBlockedParams = {},
    options?: CallOptions,
  ): Paginator<BlockedContact, ContactsListBlockedParams> {
    return this._list<BlockedContact, ContactsListBlockedParams>(
      `/v1/accounts/${enc(accountId)}/blocklist`,
      params,
      (p) => ({ limit: p.limit, cursor: p.cursor }),
      options,
    );
  }

  /**
   * Get the account's contact link
   *
   * The account's own contact QR link.
   *
   * `GET /v1/accounts/{accountId}/contact-link`
   */
  getLink(accountId: string, options?: CallOptions): Promise<ContactLink> {
    return this._request<ContactLink>("GET", `/v1/accounts/${enc(accountId)}/contact-link`, {}, options);
  }

  /**
   * Reset the account's contact link
   *
   * Revoke the current contact link and return a new one.
   *
   * `POST /v1/accounts/{accountId}/contact-link/reset`
   */
  resetLink(accountId: string, options?: CallOptions): Promise<ContactLink> {
    return this._request<ContactLink>(
      "POST",
      `/v1/accounts/${enc(accountId)}/contact-link/reset`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Resolve a contact or business link
   *
   * Who a contact QR link or a business message link points to. Read-only. `400 not_supported` when WhatsApp does not offer link resolution to this account.
   *
   * `POST /v1/accounts/{accountId}/links/resolve`
   */
  resolveLink(
    accountId: string,
    params: ContactsResolveLinkParams,
    options?: CallOptions,
  ): Promise<ResolvedLink> {
    return this._request<ResolvedLink>(
      "POST",
      `/v1/accounts/${enc(accountId)}/links/resolve`,
      { body: params, idempotent: true },
      options,
    );
  }
}
