// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { Resource } from "./base.js";
import { EventStream, type StreamOptions, type StreamSpec } from "../stream.js";
import type { WebhookEvent, WebhookEventType } from "../types.js";

/** The stream, as the generator's config describes it: what the runtime works from. */
export const STREAM_SPEC: StreamSpec = {
  baseUrl: "https://stream.wuapi.dev",
  path: "/v1/events/stream",
  resumeHeader: "Last-Event-ID",
  resetEvent: "reset",
  timing: {
    retryMs: 3000,
    heartbeatMs: 15000,
    idleTimeoutMs: 45000,
    openTimeoutMs: 12000,
    backoffBaseMs: 1000,
    backoffCapMs: 30000,
    minGapMs: 1000,
    stableAfterMs: 30000,
    retryMaxMs: 60000,
    retryAfterMaxMs: 300000,
    replayWindowMs: 1800000,
  },
  limits: {
    connectBudget: 6,
    connectBudgetWindowMs: 60000,
    maxFrameBytes: 1048576,
    dedupeWindow: 2048,
  },
  refusals: [
    { status: 400, error: "invalid_request" },
    { status: 401, error: "unauthorized", apiOnly: true },
    { status: 403, error: "forbidden" },
    { status: 404, error: "not_found" },
    { status: 429, code: "stream_connection_limit", waitMs: 30000 },
    { status: 429, waitMs: 60000 },
  ],
};

/** The values `types` takes: every `WebhookEventType` the stream carries. */
export type StreamEventType = Exclude<WebhookEventType, "chat.presence_updated" | "contact.presence_updated" | "webhook.test">;

/** Why a stream could not resume: the `reason` of a `reset` item. */
export type StreamResetReason = "cursor_expired" | "cursor_unknown" | "not_logged";

/** What `events.stream` takes. */
export interface EventsStreamParams<T extends StreamEventType = StreamEventType> {
  /** Only these event types. Presence events and `webhook.test` are not on Streams. At most 50. */
  types?: readonly T[];
  /** Only these accounts, by id. At most 50. */
  accounts?: readonly string[];
  /**
   * Resume after this cursor: the `cursor` of the last event you handled, or a stream's `lastEventId`. Sent as `Last-Event-ID`.
   */
  lastEventId?: string;
}

/**
 * Streams: your events over one connection your code opens, the same envelope a webhook carries. No public endpoint needed.
 */
export class EventsResource extends Resource {
  /**
   * Streams: your events over one connection your code opens, the same envelope a webhook carries. No public endpoint needed.
   *
   * Opens the stream. Iterate the result with `for await` for the events; it reconnects and resumes by itself, and ends only when it is closed (`options.signal`, `close()`) or on a `StreamError`.
   *
   * `GET https://stream.wuapi.dev/v1/events/stream`
   */
  stream<T extends StreamEventType = StreamEventType>(params: EventsStreamParams<T> = {}, options: StreamOptions = {}): EventStream<Extract<WebhookEvent, { type: T }>> {
    return new EventStream(
      this.http,
      STREAM_SPEC,
      { filters: { types: params.types, accounts: params.accounts }, lastEventId: params.lastEventId },
      options,
    );
  }
}
