// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { enc, type CallOptions } from "../core.js";
import type { Paginator } from "../pagination.js";
import type {
  CommunityParticipant,
  Group,
  GroupInviteLink,
  GroupJoin,
  GroupJoinRequest,
  GroupsAddParticipantsParams,
  GroupsApproveJoinRequestsParams,
  GroupsCreateParams,
  GroupsDemoteParticipantsParams,
  GroupsJoinParams,
  GroupsLinkSubgroupParams,
  GroupsListCommunityParticipantsParams,
  GroupsListJoinRequestsParams,
  GroupsListParams,
  GroupsListSubgroupsParams,
  GroupsPromoteParticipantsParams,
  GroupsRejectJoinRequestsParams,
  GroupsRemoveParticipantsParams,
  GroupsSetPictureParams,
  GroupsUpdateParams,
  ParticipantResult,
  ParticipantResultList,
  Picture,
  Subgroup,
} from "../types.js";
import { Resource } from "./base.js";

export class GroupsResource extends Resource {
  /**
   * List groups
   *
   * Every group of the account, read live from WhatsApp.
   *
   * `GET /v1/accounts/{accountId}/groups`
   */
  list(
    accountId: string,
    params: GroupsListParams = {},
    options?: CallOptions,
  ): Paginator<Group, GroupsListParams> {
    return this._list<Group, GroupsListParams>(
      `/v1/accounts/${enc(accountId)}/groups`,
      params,
      (p) => ({ limit: p.limit, cursor: p.cursor }),
      options,
    );
  }

  /**
   * Create a group or community
   *
   * With `community: true`, creates a community (`participants` may be empty); link groups to it with `POST .../groups/{groupId}/subgroups`.
   *
   * `POST /v1/accounts/{accountId}/groups`
   */
  create(accountId: string, params: GroupsCreateParams, options?: CallOptions): Promise<Group> {
    return this._request<Group>(
      "POST",
      `/v1/accounts/${enc(accountId)}/groups`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Join a group by invite
   *
   * Join with an invite code or link.
   *
   * `POST /v1/accounts/{accountId}/groups/join`
   */
  join(accountId: string, params: GroupsJoinParams, options?: CallOptions): Promise<GroupJoin>;
  /** @deprecated Pass `{ code }`. This positional form goes away in 1.0. */
  join(accountId: string, code: string, options?: CallOptions): Promise<GroupJoin>;
  join(accountId: string, params: GroupsJoinParams | string, options?: CallOptions): Promise<GroupJoin> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<GroupJoin>(
        "POST",
        `/v1/accounts/${enc(accountId)}/groups/join`,
        { body: { code: params }, idempotent: true },
        options,
      );
    }
    return this._request<GroupJoin>(
      "POST",
      `/v1/accounts/${enc(accountId)}/groups/join`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Preview a group invite
   *
   * The group behind an invite code, without joining.
   *
   * `GET /v1/accounts/{accountId}/groups/invites/{code}`
   */
  getInvite(accountId: string, code: string, options?: CallOptions): Promise<Group> {
    return this._request<Group>(
      "GET",
      `/v1/accounts/${enc(accountId)}/groups/invites/${enc(code)}`,
      {},
      options,
    );
  }

  /**
   * Get a group
   *
   * The group and its participants, read live from WhatsApp.
   *
   * `GET /v1/accounts/{accountId}/groups/{groupId}`
   */
  get(accountId: string, groupId: string, options?: CallOptions): Promise<Group> {
    return this._request<Group>("GET", `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}`, {}, options);
  }

  /**
   * Update a group
   *
   * Change the name, description or settings. Admins only.
   *
   * `PATCH /v1/accounts/{accountId}/groups/{groupId}`
   */
  update(
    accountId: string,
    groupId: string,
    params: GroupsUpdateParams = {},
    options?: CallOptions,
  ): Promise<Group> {
    return this._request<Group>(
      "PATCH",
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}`,
      { body: params },
      options,
    );
  }

  /**
   * Leave a group
   *
   * The account leaves the group.
   *
   * `POST /v1/accounts/{accountId}/groups/{groupId}/leave`
   */
  leave(accountId: string, groupId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/leave`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Add participants
   *
   * Add contacts to the group. A contact whose privacy forbids it gets an `inviteCode` instead. Each contact gets its own result.
   *
   * `POST /v1/accounts/{accountId}/groups/{groupId}/participants/add`
   */
  addParticipants(
    accountId: string,
    groupId: string,
    params: GroupsAddParticipantsParams,
    options?: CallOptions,
  ): Promise<ParticipantResultList>;
  /**
   * @deprecated Pass `{ contactIds }` and read `items` of the result. This positional form and its bare result go away in 1.0.
   */
  addParticipants(
    accountId: string,
    groupId: string,
    contactIds: string[],
    options?: CallOptions,
  ): Promise<ParticipantResult[]>;
  addParticipants(
    accountId: string,
    groupId: string,
    params: GroupsAddParticipantsParams | string[],
    options?: CallOptions,
  ): Promise<ParticipantResultList | ParticipantResult[]> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<ParticipantResultList>(
        "POST",
        `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/participants/add`,
        { body: { contactIds: params }, idempotent: true },
        options,
      ).then((res) => res.items);
    }
    return this._request<ParticipantResultList>(
      "POST",
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/participants/add`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Remove participants
   *
   * Remove contacts from the group. Each contact gets its own result.
   *
   * `POST /v1/accounts/{accountId}/groups/{groupId}/participants/remove`
   */
  removeParticipants(
    accountId: string,
    groupId: string,
    params: GroupsRemoveParticipantsParams,
    options?: CallOptions,
  ): Promise<ParticipantResultList>;
  /**
   * @deprecated Pass `{ contactIds }` and read `items` of the result. This positional form and its bare result go away in 1.0.
   */
  removeParticipants(
    accountId: string,
    groupId: string,
    contactIds: string[],
    options?: CallOptions,
  ): Promise<ParticipantResult[]>;
  removeParticipants(
    accountId: string,
    groupId: string,
    params: GroupsRemoveParticipantsParams | string[],
    options?: CallOptions,
  ): Promise<ParticipantResultList | ParticipantResult[]> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<ParticipantResultList>(
        "POST",
        `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/participants/remove`,
        { body: { contactIds: params }, idempotent: true },
        options,
      ).then((res) => res.items);
    }
    return this._request<ParticipantResultList>(
      "POST",
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/participants/remove`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Promote participants
   *
   * Make participants admins. Each contact gets its own result.
   *
   * `POST /v1/accounts/{accountId}/groups/{groupId}/participants/promote`
   */
  promoteParticipants(
    accountId: string,
    groupId: string,
    params: GroupsPromoteParticipantsParams,
    options?: CallOptions,
  ): Promise<ParticipantResultList>;
  /**
   * @deprecated Pass `{ contactIds }` and read `items` of the result. This positional form and its bare result go away in 1.0.
   */
  promoteParticipants(
    accountId: string,
    groupId: string,
    contactIds: string[],
    options?: CallOptions,
  ): Promise<ParticipantResult[]>;
  promoteParticipants(
    accountId: string,
    groupId: string,
    params: GroupsPromoteParticipantsParams | string[],
    options?: CallOptions,
  ): Promise<ParticipantResultList | ParticipantResult[]> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<ParticipantResultList>(
        "POST",
        `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/participants/promote`,
        { body: { contactIds: params }, idempotent: true },
        options,
      ).then((res) => res.items);
    }
    return this._request<ParticipantResultList>(
      "POST",
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/participants/promote`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Demote participants
   *
   * Make admins regular participants. Each contact gets its own result.
   *
   * `POST /v1/accounts/{accountId}/groups/{groupId}/participants/demote`
   */
  demoteParticipants(
    accountId: string,
    groupId: string,
    params: GroupsDemoteParticipantsParams,
    options?: CallOptions,
  ): Promise<ParticipantResultList>;
  /**
   * @deprecated Pass `{ contactIds }` and read `items` of the result. This positional form and its bare result go away in 1.0.
   */
  demoteParticipants(
    accountId: string,
    groupId: string,
    contactIds: string[],
    options?: CallOptions,
  ): Promise<ParticipantResult[]>;
  demoteParticipants(
    accountId: string,
    groupId: string,
    params: GroupsDemoteParticipantsParams | string[],
    options?: CallOptions,
  ): Promise<ParticipantResultList | ParticipantResult[]> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<ParticipantResultList>(
        "POST",
        `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/participants/demote`,
        { body: { contactIds: params }, idempotent: true },
        options,
      ).then((res) => res.items);
    }
    return this._request<ParticipantResultList>(
      "POST",
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/participants/demote`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Get the invite link
   *
   * The group's current invite link. Admins only.
   *
   * `GET /v1/accounts/{accountId}/groups/{groupId}/invite-link`
   */
  getInviteLink(accountId: string, groupId: string, options?: CallOptions): Promise<GroupInviteLink> {
    return this._request<GroupInviteLink>(
      "GET",
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/invite-link`,
      {},
      options,
    );
  }

  /**
   * Reset the invite link
   *
   * Revoke the current invite link and return a new one. Admins only.
   *
   * `POST /v1/accounts/{accountId}/groups/{groupId}/invite-link/reset`
   */
  resetInviteLink(accountId: string, groupId: string, options?: CallOptions): Promise<GroupInviteLink> {
    return this._request<GroupInviteLink>(
      "POST",
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/invite-link/reset`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Set a group's picture
   *
   * JPEG. Admins only.
   *
   * `PUT /v1/accounts/{accountId}/groups/{groupId}/picture`
   */
  setPicture(
    accountId: string,
    groupId: string,
    params: GroupsSetPictureParams,
    options?: CallOptions,
  ): Promise<Picture> {
    return this._request<Picture>(
      "PUT",
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/picture`,
      { body: params },
      options,
    );
  }

  /**
   * Delete a group's picture
   *
   * Admins only.
   *
   * `DELETE /v1/accounts/{accountId}/groups/{groupId}/picture`
   */
  deletePicture(accountId: string, groupId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "DELETE",
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/picture`,
      {},
      options,
    );
  }

  /**
   * List join requests
   *
   * Pending requests to join the group. Admins only.
   *
   * `GET /v1/accounts/{accountId}/groups/{groupId}/join-requests`
   */
  listJoinRequests(
    accountId: string,
    groupId: string,
    params: GroupsListJoinRequestsParams = {},
    options?: CallOptions,
  ): Paginator<GroupJoinRequest, GroupsListJoinRequestsParams> {
    return this._list<GroupJoinRequest, GroupsListJoinRequestsParams>(
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/join-requests`,
      params,
      (p) => ({ limit: p.limit, cursor: p.cursor }),
      options,
    );
  }

  /**
   * Approve join requests
   *
   * Approve pending requests. Admins only. Each contact gets its own result.
   *
   * `POST /v1/accounts/{accountId}/groups/{groupId}/join-requests/approve`
   */
  approveJoinRequests(
    accountId: string,
    groupId: string,
    params: GroupsApproveJoinRequestsParams,
    options?: CallOptions,
  ): Promise<ParticipantResultList>;
  /**
   * @deprecated Pass `{ contactIds }` and read `items` of the result. This positional form and its bare result go away in 1.0.
   */
  approveJoinRequests(
    accountId: string,
    groupId: string,
    contactIds: string[],
    options?: CallOptions,
  ): Promise<ParticipantResult[]>;
  approveJoinRequests(
    accountId: string,
    groupId: string,
    params: GroupsApproveJoinRequestsParams | string[],
    options?: CallOptions,
  ): Promise<ParticipantResultList | ParticipantResult[]> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<ParticipantResultList>(
        "POST",
        `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/join-requests/approve`,
        { body: { contactIds: params }, idempotent: true },
        options,
      ).then((res) => res.items);
    }
    return this._request<ParticipantResultList>(
      "POST",
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/join-requests/approve`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Reject join requests
   *
   * Reject pending requests. Admins only. Each contact gets its own result.
   *
   * `POST /v1/accounts/{accountId}/groups/{groupId}/join-requests/reject`
   */
  rejectJoinRequests(
    accountId: string,
    groupId: string,
    params: GroupsRejectJoinRequestsParams,
    options?: CallOptions,
  ): Promise<ParticipantResultList>;
  /**
   * @deprecated Pass `{ contactIds }` and read `items` of the result. This positional form and its bare result go away in 1.0.
   */
  rejectJoinRequests(
    accountId: string,
    groupId: string,
    contactIds: string[],
    options?: CallOptions,
  ): Promise<ParticipantResult[]>;
  rejectJoinRequests(
    accountId: string,
    groupId: string,
    params: GroupsRejectJoinRequestsParams | string[],
    options?: CallOptions,
  ): Promise<ParticipantResultList | ParticipantResult[]> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<ParticipantResultList>(
        "POST",
        `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/join-requests/reject`,
        { body: { contactIds: params }, idempotent: true },
        options,
      ).then((res) => res.items);
    }
    return this._request<ParticipantResultList>(
      "POST",
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/join-requests/reject`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * List a community's groups
   *
   * Groups linked to the community.
   *
   * `GET /v1/accounts/{accountId}/groups/{groupId}/subgroups`
   */
  listSubgroups(
    accountId: string,
    groupId: string,
    params: GroupsListSubgroupsParams = {},
    options?: CallOptions,
  ): Paginator<Subgroup, GroupsListSubgroupsParams> {
    return this._list<Subgroup, GroupsListSubgroupsParams>(
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/subgroups`,
      params,
      (p) => ({ limit: p.limit, cursor: p.cursor }),
      options,
    );
  }

  /**
   * Link a group to a community
   *
   * Admins of both only.
   *
   * `POST /v1/accounts/{accountId}/groups/{groupId}/subgroups`
   */
  linkSubgroup(
    accountId: string,
    groupId: string,
    params: GroupsLinkSubgroupParams,
    options?: CallOptions,
  ): Promise<void>;
  /** @deprecated Pass `{ groupId }`. This positional form goes away in 1.0. */
  linkSubgroup(
    accountId: string,
    groupId: string,
    groupIdValue: string,
    options?: CallOptions,
  ): Promise<void>;
  linkSubgroup(
    accountId: string,
    groupId: string,
    params: GroupsLinkSubgroupParams | string,
    options?: CallOptions,
  ): Promise<void> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<void>(
        "POST",
        `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/subgroups`,
        { body: { groupId: params }, idempotent: true },
        options,
      );
    }
    return this._request<void>(
      "POST",
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/subgroups`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Unlink a group from a community
   *
   * Admins only.
   *
   * `DELETE /v1/accounts/{accountId}/groups/{groupId}/subgroups/{subgroupId}`
   */
  unlinkSubgroup(
    accountId: string,
    groupId: string,
    subgroupId: string,
    options?: CallOptions,
  ): Promise<void> {
    return this._request<void>(
      "DELETE",
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/subgroups/${enc(subgroupId)}`,
      {},
      options,
    );
  }

  /**
   * List a community's members
   *
   * Members across the community's linked groups.
   *
   * `GET /v1/accounts/{accountId}/groups/{groupId}/community-participants`
   */
  listCommunityParticipants(
    accountId: string,
    groupId: string,
    params: GroupsListCommunityParticipantsParams = {},
    options?: CallOptions,
  ): Paginator<CommunityParticipant, GroupsListCommunityParticipantsParams> {
    return this._list<CommunityParticipant, GroupsListCommunityParticipantsParams>(
      `/v1/accounts/${enc(accountId)}/groups/${enc(groupId)}/community-participants`,
      params,
      (p) => ({ limit: p.limit, cursor: p.cursor }),
      options,
    );
  }
}
