// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { enc, type CallOptions } from "../core.js";
import type { Paginator } from "../pagination.js";
import type { Invitation, InvitationsCreateParams, InvitationsListParams } from "../types.js";
import { Resource } from "./base.js";

/**
 * A hosted page you send to someone else, your customer, a store manager or a sales rep, so they link their own WhatsApp into one of your projects without an account, a dashboard or an API key. The page is public at `https://wuapi.dev/invite/{token}`, `noindex`, and shows nothing about your other projects, accounts or invitations.
 */
export class InvitationsResource extends Resource {
  /**
   * Create an invitation
   *
   * A hosted page (`url`) where someone else links their own WhatsApp into your project: they pick where the number's proxy exits (unless you set `proxyLocation`), then scan a QR code or type a pairing code. The account is created in the project when they start, and `invitation.status_changed` fires at each step. With `inviteeEmail`, the invitation is emailed when email is enabled (`emailSentAt`).
   *
   * `POST /v1/invitations`
   */
  create(params: InvitationsCreateParams = {}, options?: CallOptions): Promise<Invitation> {
    return this._request<Invitation>("POST", "/v1/invitations", { body: params, idempotent: true }, options);
  }

  /**
   * List invitations
   *
   * Invitations in scope, newest first. `url` is always `null` here.
   *
   * `GET /v1/invitations`
   */
  list(
    params: InvitationsListParams = {},
    options?: CallOptions,
  ): Paginator<Invitation, InvitationsListParams> {
    return this._list<Invitation, InvitationsListParams>(
      "/v1/invitations",
      params,
      (p) => ({ status: p.status, limit: p.limit, cursor: p.cursor, projectId: p.projectId }),
      options,
    );
  }

  /**
   * Get an invitation
   *
   * `url` is always `null` here.
   *
   * `GET /v1/invitations/{invitationId}`
   */
  get(invitationId: string, options?: CallOptions): Promise<Invitation> {
    return this._request<Invitation>("GET", `/v1/invitations/${enc(invitationId)}`, {}, options);
  }

  /**
   * Cancel an invitation
   *
   * The link stops working. Cancelling a cancelled invitation changes nothing. An account the invitee already started stays in the project, unlinked.
   *
   * `POST /v1/invitations/{invitationId}/cancel`
   */
  cancel(invitationId: string, options?: CallOptions): Promise<Invitation> {
    return this._request<Invitation>(
      "POST",
      `/v1/invitations/${enc(invitationId)}/cancel`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Resend an invitation
   *
   * Rotates the token (the old `url` stops working), moves the invitation back to `pending` with a new expiry of the same length, and emails it again when it has an `inviteeEmail`. An account the invitee started is kept, so they resume where they left off.
   *
   * `POST /v1/invitations/{invitationId}/resend`
   */
  resend(invitationId: string, options?: CallOptions): Promise<Invitation> {
    return this._request<Invitation>(
      "POST",
      `/v1/invitations/${enc(invitationId)}/resend`,
      { idempotent: true },
      options,
    );
  }
}
