// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { enc, type CallOptions } from "../core.js";
import type { Label, LabelsUpsertParams } from "../types.js";
import { Resource } from "./base.js";

export class LabelsResource extends Resource {
  /**
   * Create or edit a label
   *
   * Creates the label with this id, or edits it. WhatsApp Business accounts only; others answer `400 not_supported`.
   *
   * `PUT /v1/accounts/{accountId}/labels/{labelId}`
   */
  upsert(
    accountId: string,
    labelId: string,
    params: LabelsUpsertParams,
    options?: CallOptions,
  ): Promise<Label> {
    return this._request<Label>(
      "PUT",
      `/v1/accounts/${enc(accountId)}/labels/${enc(labelId)}`,
      { body: params },
      options,
    );
  }

  /**
   * Delete a label
   *
   * WhatsApp Business accounts only.
   *
   * `DELETE /v1/accounts/{accountId}/labels/{labelId}`
   */
  delete(accountId: string, labelId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "DELETE",
      `/v1/accounts/${enc(accountId)}/labels/${enc(labelId)}`,
      {},
      options,
    );
  }
}
