// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { enc, type CallOptions } from "../core.js";
import type { Paginator } from "../pagination.js";
import type {
  Message,
  MessageMediaFile,
  MessagesAddLabelParams,
  MessagesDeleteParams,
  MessagesEditParams,
  MessagesGetMediaParams,
  MessagesListParams,
  MessagesReactParams,
  MessagesSendParams,
  MessagesVoteParams,
} from "../types.js";
import { Resource } from "./base.js";

export class MessagesResource extends Resource {
  /**
   * Send a message
   *
   * Queue a message from a `ready` account to a contact, a group, or a channel the account administers. It is returned with `status: queued`; the outcome arrives as `message.sent` / `message.failed`, or read it with `GET /v1/messages/{messageId}`. An account that dropped from `ready` for a reconnect less than the offline tolerance ago (currently 3 minutes) still takes it: it waits for the account, is sent once the account is back (in order, with the same WhatsApp message id if an earlier attempt was cut off), and fails with `account_offline` if the account is not back within the tolerance or goes down for good (logged out, banned, replaced, deleted). The account's pacing (12 per minute and 5 per minute to first contacts by default, see `pacing` on the account) keeps it queued and retried for up to `pacing.queueTimeoutMinutes` (60 by default) before it fails with `rate_limited`. A recipient without WhatsApp fails with `error.code: not_on_whatsapp`.
   *
   * Send `Idempotency-Key` so a retry never sends twice.
   *
   * `POST /v1/messages`
   */
  send(params: MessagesSendParams, options?: CallOptions): Promise<Message> {
    return this._request<Message>("POST", "/v1/messages", { body: params, idempotent: true }, options);
  }

  /**
   * List messages
   *
   * Messages in scope, newest first.
   *
   * `GET /v1/messages`
   */
  list(params: MessagesListParams = {}, options?: CallOptions): Paginator<Message, MessagesListParams> {
    return this._list<Message, MessagesListParams>(
      "/v1/messages",
      params,
      (p) => ({ accountId: p.accountId, chatId: p.chatId, direction: p.direction, limit: p.limit, cursor: p.cursor, projectId: p.projectId }),
      options,
    );
  }

  /**
   * Get a message
   *
   * A message and its current status.
   *
   * `GET /v1/messages/{messageId}`
   */
  get(messageId: string, options?: CallOptions): Promise<Message> {
    return this._request<Message>("GET", `/v1/messages/${enc(messageId)}`, {}, options);
  }

  /**
   * Get a message's media
   *
   * The message's file. By default the answer is `302 Found` to the file (no API key needed there), so `curl -L`, browsers and HTTP clients download it directly. With `redirect=false`, or an `Accept` header that names only `application/json` (the SDKs), the answer is this JSON with the file's URL instead.
   *
   * A received file still on WhatsApp (`media.downloaded: false`, on-demand media) is downloaded first, once, through the number's proxy, and kept: later requests are served from storage. Concurrent requests for the same file wait for that one download. WhatsApp keeps files for a limited time (about two weeks), after which the answer is `410 media_expired`. The account must be `ready` for a first download.
   *
   * `GET /v1/messages/{messageId}/media`
   */
  getMedia(
    messageId: string,
    params: MessagesGetMediaParams = {},
    options?: CallOptions,
  ): Promise<MessageMediaFile> {
    return this._request<MessageMediaFile>(
      "GET",
      `/v1/messages/${enc(messageId)}/media`,
      { query: { redirect: params.redirect } },
      options,
    );
  }

  /**
   * Edit a message
   *
   * Outbound text messages only, within WhatsApp's edit window (about 15 minutes; WhatsApp's refusal is returned as is). Fires `message.edited`.
   *
   * A text message still `queued` (never sent) is sent with the new text instead: `editedAt` stays `null` and `message.edited` does not fire. While a queued message is being handed to WhatsApp this answers `409 message_sending` for a few seconds.
   *
   * `PATCH /v1/messages/{messageId}`
   */
  edit(messageId: string, params: MessagesEditParams, options?: CallOptions): Promise<Message>;
  /** @deprecated Pass `{ text }`. This positional form goes away in 1.0. */
  edit(messageId: string, text: string, options?: CallOptions): Promise<Message>;
  edit(messageId: string, params: MessagesEditParams | string, options?: CallOptions): Promise<Message> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<Message>(
        "PATCH",
        `/v1/messages/${enc(messageId)}`,
        { body: { text: params } },
        options,
      );
    }
    return this._request<Message>("PATCH", `/v1/messages/${enc(messageId)}`, { body: params }, options);
  }

  /**
   * Delete a message
   *
   * Outbound messages only. For everyone by default: the row stays with `deletedAt` set and its content cleared, and `message.deleted` fires.
   *
   * A message still `queued` (never sent) is cancelled instead: it never goes out, it ends `failed` with `error.code: cancelled`, and `message.failed` fires. While a queued message is being handed to WhatsApp this answers `409 message_sending` for a few seconds.
   *
   * `DELETE /v1/messages/{messageId}`
   */
  delete(messageId: string, params: MessagesDeleteParams = {}, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "DELETE",
      `/v1/messages/${enc(messageId)}`,
      { query: { forEveryone: params.forEveryone } },
      options,
    );
  }

  /**
   * React to a message
   *
   * An empty `emoji` removes the reaction.
   *
   * `POST /v1/messages/{messageId}/react`
   */
  react(messageId: string, params: MessagesReactParams, options?: CallOptions): Promise<void>;
  /** @deprecated Pass `{ emoji }`. This positional form goes away in 1.0. */
  react(messageId: string, emoji: string, options?: CallOptions): Promise<void>;
  react(messageId: string, params: MessagesReactParams | string, options?: CallOptions): Promise<void> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<void>(
        "POST",
        `/v1/messages/${enc(messageId)}/react`,
        { body: { emoji: params }, idempotent: true },
        options,
      );
    }
    return this._request<void>(
      "POST",
      `/v1/messages/${enc(messageId)}/react`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Vote in a poll
   *
   * Options are validated against the stored poll. Returns the poll with its tally, your vote included.
   *
   * `POST /v1/messages/{messageId}/vote`
   */
  vote(messageId: string, params: MessagesVoteParams, options?: CallOptions): Promise<Message>;
  /** @deprecated Pass `{ options }`. This positional form goes away in 1.0. */
  vote(messageId: string, optionsValue: string[], options?: CallOptions): Promise<Message>;
  vote(messageId: string, params: MessagesVoteParams | string[], options?: CallOptions): Promise<Message> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<Message>(
        "POST",
        `/v1/messages/${enc(messageId)}/vote`,
        { body: { options: params }, idempotent: true },
        options,
      );
    }
    return this._request<Message>(
      "POST",
      `/v1/messages/${enc(messageId)}/vote`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Star a message
   *
   * Star the message on the phone and other devices.
   *
   * `POST /v1/messages/{messageId}/star`
   */
  star(messageId: string, options?: CallOptions): Promise<Message> {
    return this._request<Message>(
      "POST",
      `/v1/messages/${enc(messageId)}/star`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Unstar a message
   *
   * Remove the star.
   *
   * `POST /v1/messages/{messageId}/unstar`
   */
  unstar(messageId: string, options?: CallOptions): Promise<Message> {
    return this._request<Message>(
      "POST",
      `/v1/messages/${enc(messageId)}/unstar`,
      { idempotent: true },
      options,
    );
  }

  /**
   * Label a message
   *
   * WhatsApp Business accounts only. The message must have reached WhatsApp and not be deleted.
   *
   * `POST /v1/messages/{messageId}/labels`
   */
  addLabel(messageId: string, params: MessagesAddLabelParams, options?: CallOptions): Promise<void>;
  /** @deprecated Pass `{ labelId }`. This positional form goes away in 1.0. */
  addLabel(messageId: string, labelId: string, options?: CallOptions): Promise<void>;
  addLabel(messageId: string, params: MessagesAddLabelParams | string, options?: CallOptions): Promise<void> {
    if (typeof params !== "object" || Array.isArray(params)) {
      return this._request<void>(
        "POST",
        `/v1/messages/${enc(messageId)}/labels`,
        { body: { labelId: params }, idempotent: true },
        options,
      );
    }
    return this._request<void>(
      "POST",
      `/v1/messages/${enc(messageId)}/labels`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Remove a label from a message
   *
   * WhatsApp Business accounts only.
   *
   * `DELETE /v1/messages/{messageId}/labels/{labelId}`
   */
  removeLabel(messageId: string, labelId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "DELETE",
      `/v1/messages/${enc(messageId)}/labels/${enc(labelId)}`,
      {},
      options,
    );
  }
}
