// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { enc, type CallOptions } from "../core.js";
import type { Order, OrdersGetParams } from "../types.js";
import { Resource } from "./base.js";

/** Catalog orders contacts send as messages, read live from WhatsApp. */
export class OrdersResource extends Resource {
  /**
   * Get an order
   *
   * Details of a catalog order received as a message.
   *
   * `GET /v1/accounts/{accountId}/orders/{orderId}`
   */
  get(accountId: string, orderId: string, params: OrdersGetParams, options?: CallOptions): Promise<Order> {
    return this._request<Order>(
      "GET",
      `/v1/accounts/${enc(accountId)}/orders/${enc(orderId)}`,
      { query: { token: params.token } },
      options,
    );
  }
}
