// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { enc, type CallOptions } from "../core.js";
import type { PrivacySettings, PrivacyUpdateParams, StoryPrivacy } from "../types.js";
import { Resource } from "./base.js";

/** The linked number's privacy settings. */
export class PrivacyResource extends Resource {
  /**
   * Get privacy settings
   *
   * The account's privacy settings, read live from WhatsApp.
   *
   * `GET /v1/accounts/{accountId}/privacy`
   */
  get(accountId: string, options?: CallOptions): Promise<PrivacySettings> {
    return this._request<PrivacySettings>("GET", `/v1/accounts/${enc(accountId)}/privacy`, {}, options);
  }

  /**
   * Change privacy settings
   *
   * Change one or more settings. Each setting is one change on WhatsApp. Returns every setting after the change.
   *
   * `PATCH /v1/accounts/{accountId}/privacy`
   */
  update(
    accountId: string,
    params: PrivacyUpdateParams = {},
    options?: CallOptions,
  ): Promise<PrivacySettings> {
    return this._request<PrivacySettings>(
      "PATCH",
      `/v1/accounts/${enc(accountId)}/privacy`,
      { body: params },
      options,
    );
  }

  /**
   * Get story privacy
   *
   * Who sees the account's stories.
   *
   * `GET /v1/accounts/{accountId}/privacy/stories`
   */
  getStoryPrivacy(accountId: string, options?: CallOptions): Promise<StoryPrivacy> {
    return this._request<StoryPrivacy>("GET", `/v1/accounts/${enc(accountId)}/privacy/stories`, {}, options);
  }
}
