// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { enc, type CallOptions } from "../core.js";
import type { Picture, ProfileSetPictureParams, ProfileUpdateParams } from "../types.js";
import { Resource } from "./base.js";

/** The linked number's own About text, display name and picture. */
export class ProfileResource extends Resource {
  /**
   * Update the About text or display name
   *
   * WhatsApp cannot be read back here, so this answers 204. `about` and `name` are two changes on WhatsApp.
   *
   * `PATCH /v1/accounts/{accountId}/profile`
   */
  update(accountId: string, params: ProfileUpdateParams = {}, options?: CallOptions): Promise<void> {
    return this._request<void>("PATCH", `/v1/accounts/${enc(accountId)}/profile`, { body: params }, options);
  }

  /**
   * Set the profile picture
   *
   * JPEG, from an https URL or base64.
   *
   * `PUT /v1/accounts/{accountId}/profile/picture`
   */
  setPicture(accountId: string, params: ProfileSetPictureParams, options?: CallOptions): Promise<Picture> {
    return this._request<Picture>(
      "PUT",
      `/v1/accounts/${enc(accountId)}/profile/picture`,
      { body: params },
      options,
    );
  }

  /**
   * Delete the profile picture
   *
   * Remove the account's profile picture.
   *
   * `DELETE /v1/accounts/{accountId}/profile/picture`
   */
  deletePicture(accountId: string, options?: CallOptions): Promise<void> {
    return this._request<void>("DELETE", `/v1/accounts/${enc(accountId)}/profile/picture`, {}, options);
  }
}
