// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { enc, type CallOptions, type HttpClient } from "../core.js";
import type { Paginator } from "../pagination.js";
import type {
  ApiKey,
  Project,
  ProjectUsage,
  ProjectsApiKeysCreateParams,
  ProjectsApiKeysListParams,
  ProjectsCreateParams,
  ProjectsGetUsageParams,
  ProjectsListParams,
  ProjectsUpdateParams,
} from "../types.js";
import { Resource } from "./base.js";

/** API keys scoped to one project. */
export class ProjectsApiKeysResource extends Resource {
  /**
   * List a project's API keys
   *
   * Every key of the project, revoked ones included. Never the key itself. Organization keys only (project keys get `403 forbidden`); the `Wuapi-Project` header does not change the result.
   *
   * `GET /v1/projects/{projectId}/api-keys`
   */
  list(
    projectId: string,
    params: ProjectsApiKeysListParams = {},
    options?: CallOptions,
  ): Paginator<ApiKey, ProjectsApiKeysListParams> {
    return this._list<ApiKey, ProjectsApiKeysListParams>(
      `/v1/projects/${enc(projectId)}/api-keys`,
      params,
      (p) => ({ limit: p.limit, cursor: p.cursor }),
      options,
    );
  }

  /**
   * Create a project API key
   *
   * A key that reaches only this project's resources. At most 20 active keys per project. The `key` is shown only here. Organization keys only (project keys get `403 forbidden`); the `Wuapi-Project` header does not change the result.
   *
   * `POST /v1/projects/{projectId}/api-keys`
   */
  create(projectId: string, params: ProjectsApiKeysCreateParams, options?: CallOptions): Promise<ApiKey> {
    return this._request<ApiKey>(
      "POST",
      `/v1/projects/${enc(projectId)}/api-keys`,
      { body: params, idempotent: true },
      options,
    );
  }

  /**
   * Revoke a project API key
   *
   * The key stops working at once. Organization keys only (project keys get `403 forbidden`); the `Wuapi-Project` header does not change the result.
   *
   * `DELETE /v1/projects/{projectId}/api-keys/{apiKeyId}`
   */
  revoke(projectId: string, apiKeyId: string, options?: CallOptions): Promise<void> {
    return this._request<void>(
      "DELETE",
      `/v1/projects/${enc(projectId)}/api-keys/${enc(apiKeyId)}`,
      {},
      options,
    );
  }
}

export class ProjectsResource extends Resource {
  /** API keys scoped to one project. */
  readonly apiKeys: ProjectsApiKeysResource;

  constructor(http: HttpClient) {
    super(http);
    this.apiKeys = new ProjectsApiKeysResource(http);
  }

  /**
   * Create a project
   *
   * Fires `project.created`. Organization keys only (project keys get `403 forbidden`); the `Wuapi-Project` header does not change the result.
   *
   * `POST /v1/projects`
   */
  create(params: ProjectsCreateParams, options?: CallOptions): Promise<Project> {
    return this._request<Project>("POST", "/v1/projects", { body: params, idempotent: true }, options);
  }

  /**
   * List projects
   *
   * Live projects, newest first. Organization keys only (project keys get `403 forbidden`); the `Wuapi-Project` header does not change the result.
   *
   * `GET /v1/projects`
   */
  list(params: ProjectsListParams = {}, options?: CallOptions): Paginator<Project, ProjectsListParams> {
    return this._list<Project, ProjectsListParams>(
      "/v1/projects",
      params,
      (p) => ({ limit: p.limit, cursor: p.cursor, externalId: p.externalId, status: p.status }),
      options,
    );
  }

  /**
   * Get a project
   *
   * A project, by id or `ext:<externalId>`. Organization keys only (project keys get `403 forbidden`); the `Wuapi-Project` header does not change the result.
   *
   * `GET /v1/projects/{projectId}`
   */
  get(projectId: string, options?: CallOptions): Promise<Project> {
    return this._request<Project>("GET", `/v1/projects/${enc(projectId)}`, {}, options);
  }

  /**
   * Update, suspend or resume a project
   *
   * `status: suspended` refuses every send and write in the project (`403 project_suspended`) while reads and inbound keep working. Fires `project.updated`. Organization keys only (project keys get `403 forbidden`); the `Wuapi-Project` header does not change the result.
   *
   * `PATCH /v1/projects/{projectId}`
   */
  update(projectId: string, params: ProjectsUpdateParams = {}, options?: CallOptions): Promise<Project> {
    return this._request<Project>("PATCH", `/v1/projects/${enc(projectId)}`, { body: params }, options);
  }

  /**
   * Delete a project
   *
   * Answers at once: from then on the project is 404, its keys answer 401 and its `externalId` can be reused. In the background its accounts are logged out and deleted, then its webhook endpoints removed, and `project.deleted` fires. Organization keys only (project keys get `403 forbidden`); the `Wuapi-Project` header does not change the result.
   *
   * `DELETE /v1/projects/{projectId}`
   */
  delete(projectId: string, options?: CallOptions): Promise<void> {
    return this._request<void>("DELETE", `/v1/projects/${enc(projectId)}`, {}, options);
  }

  /**
   * Get a project's usage
   *
   * The project's usage for `month`. Organization keys only (project keys get `403 forbidden`); the `Wuapi-Project` header does not change the result.
   *
   * `GET /v1/projects/{projectId}/usage`
   */
  getUsage(
    projectId: string,
    params: ProjectsGetUsageParams = {},
    options?: CallOptions,
  ): Promise<ProjectUsage> {
    return this._request<ProjectUsage>(
      "GET",
      `/v1/projects/${enc(projectId)}/usage`,
      { query: { month: params.month } },
      options,
    );
  }
}
