// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { type CallOptions } from "../core.js";
import type { Paginator } from "../pagination.js";
import type { ProxyLocationItem, ProxyLocationsListParams } from "../types.js";
import { Resource } from "./base.js";

/**
 * The countries and cities an account's residential proxy can be placed in: the values `proxyLocation` accepts on `POST /v1/accounts`.
 */
export class ProxyLocationsResource extends Resource {
  /**
   * List proxy locations
   *
   * The catalog of supported `{country, city}` pairs for `proxyLocation`, ordered by country name, then by city population, largest first. Filter with `country`, or search with `q`.
   *
   * With `q`, results are ranked instead: an exact match first, then a prefix (`bogo` finds Bogotá), then a later word (`york` finds New York City), then text anywhere in the name; ties go to the bigger city. `q` matches the city name, the city code, the country name and the ISO code (`cl` returns Chile's cities first), ignoring case and accents (`sao` finds São Paulo). It combines with `country`, and pages like any list.
   *
   * `GET /v1/proxy-locations`
   */
  list(
    params: ProxyLocationsListParams = {},
    options?: CallOptions,
  ): Paginator<ProxyLocationItem, ProxyLocationsListParams> {
    return this._list<ProxyLocationItem, ProxyLocationsListParams>(
      "/v1/proxy-locations",
      params,
      (p) => ({ country: p.country, q: p.q, limit: p.limit, cursor: p.cursor }),
      options,
    );
  }
}
