// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { enc, type CallOptions } from "../core.js";
import type { StickerPack } from "../types.js";
import { Resource } from "./base.js";

/** WhatsApp sticker packs, read live from WhatsApp. */
export class StickerPacksResource extends Resource {
  /**
   * Get a sticker pack
   *
   * A sticker pack and its stickers.
   *
   * `GET /v1/accounts/{accountId}/sticker-packs/{stickerPackId}`
   */
  get(accountId: string, stickerPackId: string, options?: CallOptions): Promise<StickerPack> {
    return this._request<StickerPack>(
      "GET",
      `/v1/accounts/${enc(accountId)}/sticker-packs/${enc(stickerPackId)}`,
      {},
      options,
    );
  }
}
