// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { enc, type CallOptions } from "../core.js";
import type { Message, StoriesCreateParams } from "../types.js";
import { Resource } from "./base.js";

/** WhatsApp Status posts. A story is stored as a message whose `chatId` is `stories`. */
export class StoriesResource extends Resource {
  /**
   * Post a story
   *
   * Queued like any send and stored as an outbound message with `chatId: stories`. The outcome arrives as `message.sent` or `message.failed`.
   *
   * An image or video story takes `media.url` or `media.uploadId` (a file uploaded with `POST /v1/uploads`).
   *
   * `POST /v1/accounts/{accountId}/stories`
   */
  create(accountId: string, params: StoriesCreateParams, options?: CallOptions): Promise<Message> {
    return this._request<Message>(
      "POST",
      `/v1/accounts/${enc(accountId)}/stories`,
      { body: params, idempotent: true },
      options,
    );
  }
}
