// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { type CallOptions } from "../core.js";
import type { Usage, UsageByProjectParams, UsageReport } from "../types.js";
import { Resource } from "./base.js";

/** Billable usage, and the per-project export for rebilling. */
export class UsageResource extends Resource {
  /**
   * Get usage
   *
   * Billable usage for the current calendar month (UTC). Organization keys only (project keys get `403 forbidden`); the `Wuapi-Project` header does not change the result.
   *
   * `GET /v1/usage`
   */
  get(options?: CallOptions): Promise<Usage> {
    return this._request<Usage>("GET", "/v1/usage", {}, options);
  }

  /**
   * Get usage by project
   *
   * The rebilling export for `month` (default the current month): one line per project, plus unassigned resources and totals. Organization keys only (project keys get `403 forbidden`); the `Wuapi-Project` header does not change the result.
   *
   * `GET /v1/usage/by-project`
   */
  byProject(params: UsageByProjectParams = {}, options?: CallOptions): Promise<UsageReport> {
    return this._request<UsageReport>(
      "GET",
      "/v1/usage/by-project",
      { query: { month: params.month } },
      options,
    );
  }
}
