// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

import { HttpClient, type ClientOptions, type CallOptions } from "./core.js";
import { Resource } from "./resources/base.js";
import { AccountsResource } from "./resources/accounts.js";
import { ProxyLocationsResource } from "./resources/proxy-locations.js";
import { MessagesResource } from "./resources/messages.js";
import { StoriesResource } from "./resources/stories.js";
import { UploadsResource } from "./resources/uploads.js";
import { ChatsResource } from "./resources/chats.js";
import { LabelsResource } from "./resources/labels.js";
import { ContactsResource } from "./resources/contacts.js";
import { BotsResource } from "./resources/bots.js";
import { ProfileResource } from "./resources/profile.js";
import { PrivacyResource } from "./resources/privacy.js";
import { CallsResource } from "./resources/calls.js";
import { StickerPacksResource } from "./resources/sticker-packs.js";
import { FavoriteStickersResource } from "./resources/favorite-stickers.js";
import { OrdersResource } from "./resources/orders.js";
import { GroupsResource } from "./resources/groups.js";
import { ChannelsResource } from "./resources/channels.js";
import { WebhookEndpointsResource } from "./resources/webhook-endpoints.js";
import { ProjectsResource } from "./resources/projects.js";
import { InvitationsResource } from "./resources/invitations.js";
import { BrandingResource } from "./resources/branding.js";
import { UsageResource } from "./resources/usage.js";
import type { AuthContext } from "./types.js";

/** The wuapi API client. Secure, fast and scalable WhatsApp API for developers. */
export class Wuapi extends Resource {
  /**
   * An account is one WhatsApp number linked as a device, by QR code or by pairing code. Create one, show `qrCodeUrl` to the phone owner or have them type `pairingCode`, and wait for `ready`. Routes under `/v1/accounts/{accountId}` that talk to WhatsApp need the account `ready` (otherwise `409 account_not_ready`).
   */
  readonly accounts: AccountsResource;
  /**
   * The countries and cities an account's residential proxy can be placed in: the values `proxyLocation` accepts on `POST /v1/accounts`.
   */
  readonly proxyLocations: ProxyLocationsResource;
  readonly messages: MessagesResource;
  /** WhatsApp Status posts. */
  readonly stories: StoriesResource;
  /**
   * Send a file you have, not a URL: a local file, a pasted image, a recorded voice note. Create an upload, get its bytes to wuapi, then send it with `media: { uploadId }` on `POST /v1/messages` or a story.
   */
  readonly uploads: UploadsResource;
  readonly chats: ChatsResource;
  readonly labels: LabelsResource;
  readonly contacts: ContactsResource;
  readonly bots: BotsResource;
  /** The linked number's own About text, display name and picture. */
  readonly profile: ProfileResource;
  /** The linked number's privacy settings. */
  readonly privacy: PrivacyResource;
  /**
   * Reject incoming calls. Automatic rejection is a setting on the account (`PATCH /v1/accounts/{accountId}`).
   */
  readonly calls: CallsResource;
  /** WhatsApp sticker packs, read live from WhatsApp. */
  readonly stickerPacks: StickerPacksResource;
  /**
   * The account's favorite stickers: the star tab of WhatsApp's sticker picker, which WhatsApp keeps in sync between the phone and its linked devices.
   */
  readonly favoriteStickers: FavoriteStickersResource;
  /** Catalog orders contacts send as messages, read live from WhatsApp. */
  readonly orders: OrdersResource;
  readonly groups: GroupsResource;
  /**
   * WhatsApp channels: follow, read, react. Post with `POST /v1/messages` and `to` set to the channel id.
   */
  readonly channels: ChannelsResource;
  /**
   * wuapi sends events to your webhook endpoints as `POST` requests with a JSON body (schema `Event`):
   */
  readonly webhookEndpoints: WebhookEndpointsResource;
  readonly projects: ProjectsResource;
  /**
   * A hosted page you send to someone else, your customer, a store manager or a sales rep, so they link their own WhatsApp into one of your projects without an account, a dashboard or an API key. The page is public at `https://wuapi.dev/invite/{token}`, `noindex`, and shows nothing about your other projects, accounts or invitations.
   */
  readonly invitations: InvitationsResource;
  /**
   * What the invitation page and email show: your name, logo, accent color, support link, and whether the wuapi footer appears (hiding it needs the White label add-on).
   */
  readonly branding: BrandingResource;
  /** Billable usage, and the per-project export for rebilling. */
  readonly usage: UsageResource;

  constructor(options: ClientOptions | HttpClient = {}) {
    const http = options instanceof HttpClient ? options : new HttpClient(options);
    super(http);
    this.accounts = new AccountsResource(http);
    this.proxyLocations = new ProxyLocationsResource(http);
    this.messages = new MessagesResource(http);
    this.stories = new StoriesResource(http);
    this.uploads = new UploadsResource(http);
    this.chats = new ChatsResource(http);
    this.labels = new LabelsResource(http);
    this.contacts = new ContactsResource(http);
    this.bots = new BotsResource(http);
    this.profile = new ProfileResource(http);
    this.privacy = new PrivacyResource(http);
    this.calls = new CallsResource(http);
    this.stickerPacks = new StickerPacksResource(http);
    this.favoriteStickers = new FavoriteStickersResource(http);
    this.orders = new OrdersResource(http);
    this.groups = new GroupsResource(http);
    this.channels = new ChannelsResource(http);
    this.webhookEndpoints = new WebhookEndpointsResource(http);
    this.projects = new ProjectsResource(http);
    this.invitations = new InvitationsResource(http);
    this.branding = new BrandingResource(http);
    this.usage = new UsageResource(http);
  }

  /** The API base URL. */
  get baseUrl(): string {
    return this.http.baseUrl;
  }

  /** The project this client is scoped to (`Wuapi-Project`), if any. */
  get project(): string | undefined {
    return this.http.project;
  }

  /**
   * A client scoped to one project (its id or `ext:<externalId>`), sharing this
   * client's key and configuration. Every request carries `Wuapi-Project`.
   */
  withProject(project: string): Wuapi {
    return new Wuapi(this.http.withProject(project));
  }

  /**
   * Get the current key
   *
   * The organization, the API key and, when the request is scoped to a project, that project.
   *
   * `GET /v1/me`
   */
  me(options?: CallOptions): Promise<AuthContext> {
    return this._request<AuthContext>("GET", "/v1/me", {}, options);
  }
}
