// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

/** The version of this package. */
export const VERSION = "0.9.0";
/** The name of this package. */
export const PACKAGE_NAME = "@wuapidev/sdk";
/** The API's production URL. */
export const DEFAULT_BASE_URL = "https://api.wuapi.dev";
/** Environment variable the API key is read from. */
export const API_KEY_ENV = "WUAPI_API_KEY";
/** Header that scopes a request to a project. */
export const PROJECT_HEADER = "Wuapi-Project";
/** Header that makes a request safe to retry. */
export const IDEMPOTENCY_HEADER = "Idempotency-Key";
